/**
 * Generated by scripts/generate-icons.mjs from scripts/icon-artwork.mjs.
 * Do not edit by hand — run `npm run icons` instead.
 */
export const SHIELD_PATH = 'M256 45 C292 68 380 106 434 121 Q448 127 448 142 L448 215 C448 330 392 424 256 468 C120 424 64 330 64 215 L64 142 Q64 127 78 121 C132 106 220 68 256 45 Z';
export const SHIELD_RIGHT_PATH = 'M256 45 C292 68 380 106 434 121 Q448 127 448 142 L448 215 C448 330 392 424 256 468 Z';
export const STRIKE_LINE = 'M100 100 L420 420';
export const GLYPH_STROKE = 34;
export const SHIELD_LIGHT = '#F97316';
export const SHIELD_DARK = '#EA580C';
export const MARK_COLOR = '#FFFFFF';
export const MARK = {
  cx: 256,
  cy: 261,
  radius: 120,
  ringStroke: 31,
  slashStroke: 35,
  x1: 171.15,
  y1: 176.15,
  x2: 340.85,
  y2: 345.85,
} as const;

/** Scale factor from the 512 artwork box to the 24-unit icon grid. */
export const ARTWORK_TO_ICON_SCALE = 0.046875;
