/**
 * Generates every icon asset from the single artwork definition in icon-artwork.mjs:
 *
 *   src/assets/icon.svg    canonical vector artwork (checked in, never hand-edited)
 *   src/assets/logo.svg    same mark, for docs and the store listing
 *   public/icons/*.png     the four sizes the manifest declares
 *
 * Run with `npm run icons` after changing the artwork.
 */
import { writeFileSync } from 'node:fs';
import { mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import {
  DEFAULT_MARK,
  MARK_CENTER,
  MARK_COLOR,
  SHIELD_DARK,
  SHIELD_LIGHT,
  SHIELD_PATH,
  SHIELD_RIGHT_PATH,
  GLYPH_STROKE,
  STRIKE_LINE,
  buildIconSvg,
  markFor,
} from './icon-artwork.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SIZES = [16, 32, 48, 128];

const canonical = buildIconSvg();
writeFileSync(resolve(root, 'src/assets/icon.svg'), canonical, 'utf8');
writeFileSync(resolve(root, 'src/assets/logo.svg'), canonical, 'utf8');
console.log('icons: wrote src/assets/icon.svg and src/assets/logo.svg');

// The React UI draws the same mark inline (popup header, dashboard header, status badge),
// so the geometry is emitted as a TypeScript module rather than copy-pasted — the on-screen
// logo can never drift from the packaged PNGs.
const reach = DEFAULT_MARK.radius / Math.SQRT2;
const tsModule = `/**
 * Generated by scripts/generate-icons.mjs from scripts/icon-artwork.mjs.
 * Do not edit by hand — run \`npm run icons\` instead.
 */
export const SHIELD_PATH = '${SHIELD_PATH}';
export const SHIELD_RIGHT_PATH = '${SHIELD_RIGHT_PATH}';
export const STRIKE_LINE = '${STRIKE_LINE}';
export const GLYPH_STROKE = ${GLYPH_STROKE};
export const SHIELD_LIGHT = '${SHIELD_LIGHT}';
export const SHIELD_DARK = '${SHIELD_DARK}';
export const MARK_COLOR = '${MARK_COLOR}';
export const MARK = {
  cx: ${MARK_CENTER.x},
  cy: ${MARK_CENTER.y},
  radius: ${DEFAULT_MARK.radius},
  ringStroke: ${DEFAULT_MARK.ringStroke},
  slashStroke: ${DEFAULT_MARK.slashStroke},
  x1: ${(MARK_CENTER.x - reach).toFixed(2)},
  y1: ${(MARK_CENTER.y - reach).toFixed(2)},
  x2: ${(MARK_CENTER.x + reach).toFixed(2)},
  y2: ${(MARK_CENTER.y + reach).toFixed(2)},
} as const;

/** Scale factor from the 512 artwork box to the 24-unit icon grid. */
export const ARTWORK_TO_ICON_SCALE = ${(24 / 512).toFixed(6)};
`;
writeFileSync(resolve(root, 'src/ui/icon-artwork.ts'), tsModule, 'utf8');
console.log('icons: wrote src/ui/icon-artwork.ts');

const outDir = resolve(root, 'public/icons');
mkdirSync(outDir, { recursive: true });

for (const size of SIZES) {
  const svg = buildIconSvg({ mark: markFor(size) });
  // Rasterise well above the target, then resize down: this anti-aliases the 45° slash
  // and the ring far better than asking the SVG rasteriser for a 16px canvas directly.
  const buffer = await sharp(Buffer.from(svg), { density: 1200 })
    .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png({ compressionLevel: 9 })
    .toBuffer();
  writeFileSync(resolve(outDir, `icon-${size}.png`), buffer);
  console.log(`icons: wrote public/icons/icon-${size}.png (${buffer.length} bytes)`);
}
