/**
 * The single source of truth for the ClearBlock mark.
 *
 * The artwork is a vector trace of `src/assets/icon-source.png` (the supplied reference
 * image, kept in the repo). Geometry was measured from that file's pixels: shield bounding
 * box, the fold down the centre, and the prohibition ring's centre, radius, stroke width
 * and 45° slash. Rendering from vector rather than downsampling the 1254px PNG keeps the
 * 16px and 32px icons crisp and drops the reference image's drop shadow, which only turns
 * into a muddy halo at toolbar sizes.
 */

/** Shield silhouette in a 512x512 box, matching the reference to within ~1px at 256px. */
export const SHIELD_PATH = [
  'M256 45',
  'C292 68 380 106 434 121',
  'Q448 127 448 142',
  'L448 215',
  'C448 330 392 424 256 468',
  'C120 424 64 330 64 215',
  'L64 142',
  'Q64 127 78 121',
  'C132 106 220 68 256 45',
  'Z',
].join(' ');

/**
 * The right half of the same silhouette, used for the darker side of the centre fold.
 * Closing the subpath draws the straight vertical edge down the middle, which is exactly
 * where the fold sits — so no clipPath is needed and the artwork can be inlined into a
 * React component without any risk of duplicate element ids on the page.
 */
export const SHIELD_RIGHT_PATH = [
  'M256 45',
  'C292 68 380 106 434 121',
  'Q448 127 448 142',
  'L448 215',
  'C448 330 392 424 256 468',
  'Z',
].join(' ');

/**
 * The "protection paused" glyph draws the silhouette as an outline with a diagonal strike
 * across it. Stroking rather than cutting a hole keeps the glyph correct on any badge
 * colour — an even-odd cut-out would paint the parts of the strike that overhang the
 * silhouette. Stroke widths are in artwork units and scale down with the group.
 */
export const STRIKE_LINE = 'M100 100 L420 420';
export const GLYPH_STROKE = 34;

export const SHIELD_LIGHT = '#F97316';
export const SHIELD_DARK = '#EA580C';
export const MARK_COLOR = '#FFFFFF';

export const MARK_CENTER = { x: 256, y: 261 };

/** Measured from the reference: outer radius 135.8, ring stroke 31, slash 35 wide. */
export const DEFAULT_MARK = { radius: 120, ringStroke: 31, slashStroke: 35 };

/**
 * Optical adjustment for 16px. At that size the ring's counter fills in, so the ring is
 * thinned and pushed outwards a little to keep the "prohibited" reading legible. Standard
 * practice for an icon set; the shape is otherwise identical.
 */
export const SMALL_MARK = { radius: 122, ringStroke: 26, slashStroke: 29 };

export function markFor(size) {
  return size <= 16 ? SMALL_MARK : DEFAULT_MARK;
}

/**
 * Builds the SVG. The slash runs corner to corner at exactly 45°, ending on the ring's
 * centre radius so the two shapes merge into one mark, as they do in the reference.
 */
export function buildIconSvg({ mark = DEFAULT_MARK, size = 512, twoTone = true } = {}) {
  const reach = mark.radius / Math.SQRT2;
  const x1 = (MARK_CENTER.x - reach).toFixed(2);
  const y1 = (MARK_CENTER.y - reach).toFixed(2);
  const x2 = (MARK_CENTER.x + reach).toFixed(2);
  const y2 = (MARK_CENTER.y + reach).toFixed(2);

  const fold = twoTone
    ? `
  <!-- Right half one step deeper, reproducing the centre fold of the reference. -->
  <path d="${SHIELD_RIGHT_PATH}" fill="${SHIELD_DARK}" />`
    : '';

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="${size}" height="${size}" role="img" aria-label="ClearBlock">
  <title>ClearBlock</title>
  <!-- Generated by scripts/generate-icons.mjs from scripts/icon-artwork.mjs. Do not edit by hand. -->
  <path d="${SHIELD_PATH}" fill="${SHIELD_LIGHT}" />${fold}

  <!-- Prohibition mark: ring plus a 45° slash that merges into it. -->
  <g stroke="${MARK_COLOR}" fill="none">
    <circle cx="${MARK_CENTER.x}" cy="${MARK_CENTER.y}" r="${mark.radius}" stroke-width="${mark.ringStroke}" />
    <path d="M${x1} ${y1} L${x2} ${y2}" stroke-width="${mark.slashStroke}" />
  </g>
</svg>
`;
}
